include: package:effective_dart/analysis_options.yaml

analyzer:
  enable-experiment:
    - extension-methods

  exclude:
    - lib/**/*.gr.dart
    - lib/**/*.config.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

  errors:
    missing_return: error

    avoid_print: warning

    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    one_member_abstracts: ignore
    todo: ignore
    avoid_catches_without_on_clauses: ignore
# linter:
#   rules:
#     - prefer_const_constructors
#     - prefer_const_constructors_in_immutables
#     - prefer_const_declarations
#     - prefer_const_literals_to_create_immutables
